version: "3.8"

services:

  redis:
    image: redis:7.0.5
    ports:
      - "6379:6379"

  mongoDB:
    image: mongo:6.0.2
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME:?EMPTY MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD:?EMPTY MONGO_ROOT_PASSWORD}"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u $MONGO_ROOT_USERNAME -p $MONGO_ROOT_PASSWORD --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
  proxy:
    image: proxy
    build: ./frontProxy
    depends_on:
      - main
      - calculator
    ports:
      - "8080:8080"
    environment:
      MAIN_SERVICE_ADDRESS: "main:8085"
      CALCULATOR_SERVICE_ADDRESS: "calculator:8090"

  main:
    image: task-manager
    build: ./main
    depends_on:
      mongoDB:
        condition: service_healthy
#    restart: always
    ports:
      - "8085:8085"
    environment:
      MONGODB_URI : "mongodb://${MONGO_ROOT_USERNAME:?EMPTY MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD:?EMPTY MONGO_ROOT_PASSWORD}@mongoDB:27017/"
      CALCULATION_SERVICE_ADDRESS: "calculator:8090"

  calculator:
    image: calculator
    build: ./calculator
    depends_on:
      mongoDB:
        condition: service_healthy
    environment:
      MONGODB_URI: "mongodb://${MONGO_ROOT_USERNAME:?EMPTY MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD:?EMPTY MONGO_ROOT_PASSWORD}@mongoDB:27017/"
      REDIS_ADDRESS: "redis:6379"
    ports:
      - "8090:8090"
